### PR TITLE
enabled dependabot

### PR DESCRIPTION
**Pull request by tomellm**
#12 added every sub module as its own check to make and also the root project as there is a on that level as well.

Note that the branch name contains sonar-cloud but I decided to do that as its own PR later on.

### CODE REVIEW

**Comment by timpeeters** [comment]
Hey @tomellm I'm not 100% sure but I believe if you just add this:
```
    - package-ecosystem: "gradle" 
       directory: "/" 
       schedule:
           interval: "daily"
```

It will also cover Gradle build files in the child modules. At least, that is how it works for Maven.
Using the "Insights" tab > Dependency Graph > Dependabot we'll be able to view the logs of Dependabot once it has been merged to main.

**Comment by timpeeters** [comment]
In any case, the indentation of the file is currently not correct.

**Review by timpeeters — CHANGES_REQUESTED** [review]
Indentation not correct. I don't think this file is valid Dependabot syntax. Best to check docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#example-of-a-basic-setup-for-three-package-managers

**Comment by tomellm** [comment]
@timpeeters so it should be fine like this?

**Review by timpeeters — APPROVED** [review]

**Comment by timpeeters** [comment]
> @timpeeters so it should be fine like this?

LGTM

**Pull request merged**
